# Generated by Django 5.1.1 on 2024-09-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_rename_mome_colaborador_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='observacao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
