# Generated by Django 5.1.1 on 2024-09-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_colaborador_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='link_rstreio',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
