# Generated by Django 5.1.1 on 2024-09-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_colaborador_link_rstreio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='link_rstreio',
            new_name='link_rastreio',
        ),
    ]
