# Generated by Django 5.1.1 on 2024-09-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_rename_link_rstreio_colaborador_link_rastreio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='link_rastreio',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
