# Generated by Django 5.1.1 on 2024-09-20 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0006_alter_colaborador_link_rastreio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('memoria_ram', models.CharField(max_length=100)),
                ('armazenamento', models.CharField(max_length=100)),
                ('tipo_armazenamento', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('NVMe M.2', 'NVMe M.2')], max_length=10)),
                ('serial_number', models.CharField(max_length=100)),
                ('entregue_data', models.DateTimeField()),
                ('atribuido_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.colaborador')),
            ],
        ),
    ]
