# Generated by Django 5.1.1 on 2024-09-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='tipo_armazenamento',
            field=models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('NVMe M.2', 'NVMe M.2')], default='NVMe M.2', max_length=10),
        ),
    ]
