# Generated by Django 5.1.1 on 2024-09-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_alter_notebook_tipo_armazenamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='entregue_data',
            field=models.DateField(),
        ),
    ]
