# Generated by Django 5.1.1 on 2024-09-21 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_alter_notebook_entregue_data'),
        ('plataforma', '0006_alter_colaborador_link_rastreio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='atribuido_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plataforma.colaborador'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='entregue_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
